### ISSUE TITLE
push client readme: add usage example

### ISSUE THREAD

**Issue by derhuerst** [ParkenDD/park-api-v3#110]
Also,
- there is a type in the setup commands (`virtalenv`),
- the Docker image does not have `virtalenv`. – And if I use the push client from outside, how do I make sure that it is compatible with the ParkAPI inside the container?

**Comment by the-infinity** [comment]
Already solved for quite some time: https://github.com/ParkenDD/park-api-v3/blob/main/scripts/README.md
