### ISSUE TITLE
group attribute is documented wrong

### ISSUE THREAD

**Issue by ThorstenFroehlinghaus** [ParkenDD/park-api-v3#211]
The ParkAPI documentation sais that group is a required attribute. In fact, it should not be required because not every parking site is part of a grouping.
Should the group sub-attributed like id be marked as "required" or as "conditionally required"? They are only required of a group exists.

**Comment by the-infinity** [comment]
Fixed in https://github.com/ParkenDD/park-api-v3/pull/218
